<?php
/**
 * Copyright © 2017 Studio Raz. All rights reserved.
 * For more information contact us at dev@studioraz.co.il
 * See COPYING_STUIDRAZ.txt for license details.
 */
/**
 * @this \SR\PreviousNextNavigation\Block\Catalog\Product\PrevNextLink
 */
?>
<?php
$_helper = $this->helper('SR\PreviousNextNavigation\Helper\Data');
?>

<?php if ($this->isProductExists()): ?>
    <a href="<?php echo $this->getUrl() ?>" title="<?php echo $this->getTitle() ?>">
        <?php echo $this->getTitle() ?>
        <?php echo $this->getIsNext() ? __('(Next)') : __('(Prev)');?>
    </a>
<?php endif; ?>
